//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int A_Id { get; set; }
        public string A_UserName { get; set; }
        public string A_Password { get; set; }
        public string A_Phone { get; set; }
        public string A_Email { get; set; }
        public string A_Address { get; set; }
        public string A_Gender { get; set; }
        public string A_DateofBirth { get; set; }
        public string A_Role { get; set; }
    }
}
