//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusOwner
    {
        public int O_Id { get; set; }
        public string O_UserName { get; set; }
        public string O_Password { get; set; }
        public string O_Phone { get; set; }
        public string O_Email { get; set; }
        public string O_Address { get; set; }
        public string O_Gender { get; set; }
        public string O_DateofBirth { get; set; }
        public string O_Role { get; set; }
    }
}
