//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CR_Id { get; set; }
        public Nullable<int> U_Id { get; set; }
        public Nullable<int> B_Id { get; set; }
        public string Stopage { get; set; }
        public Nullable<int> BS_Fair { get; set; }
    
        public virtual BusInfo BusInfo { get; set; }
        public virtual User User { get; set; }
    }
}
