//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CircularBusEntities : DbContext
    {
        public CircularBusEntities()
            : base("name=CircularBusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<BusInfo> BusInfoes { get; set; }
        public DbSet<BusOwner> BusOwners { get; set; }
        public DbSet<BusRoute> BusRoutes { get; set; }
        public DbSet<Cart> Carts { get; set; }
        public DbSet<SoldTicket> SoldTickets { get; set; }
        public DbSet<Supervisor> Supervisors { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Token> Tokens { get; set; }
    }
}
