//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldTicket
    {
        public int ST_Id { get; set; }
        public Nullable<int> ST_UId { get; set; }
        public Nullable<int> ST_Quantity { get; set; }
        public Nullable<int> ST_BId { get; set; }
        public string ST_BName { get; set; }
        public string ST_BNoPlate { get; set; }
        public string ST_BType { get; set; }
        public string ST_BRoute { get; set; }
        public string ST_Status { get; set; }
    
        public virtual BusInfo BusInfo { get; set; }
        public virtual User User { get; set; }
    }
}
