//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supervisor
    {
        public int S_Id { get; set; }
        public string S_UserName { get; set; }
        public string S_Password { get; set; }
        public string S_Phone { get; set; }
        public string S_Email { get; set; }
        public string S_Address { get; set; }
        public string S_Gender { get; set; }
        public string S_DateofBirth { get; set; }
        public string S_Role { get; set; }
    }
}
